### ISSUE TITLE
[BUG]: Error: Unable to find integration meta info file

### ISSUE THREAD

**Issue by georgzoeller** [dmno-dev/dmno#123]
### dmno version

0.0.21

### Steps to reproduce

bunx dmno init

### What is expected?

Probably not an error

### What is actually happening?

✅ dmno already installed
   📦 dmno @ "^0.0.21"
✅ DMNO + astro - integration already installed
   📦 @dmno/astro-integration @ "^0.0.12"
   📚 see docs @ https://dmno.dev/docs/integrations/astro
Error: Unable to find integration meta info file
    at initDmnoForService (file:///D:/_dev/astro-playground/astro-nomy/node_modules/dmno/src/cli/lib/init-helpers.ts:90:14)
    at DmnoCommand.<anonymous> (file:///D:/_dev/astro-playground/astro-nomy/node_modules/dmno/src/cli/lib/init-helpers.ts:446:3)
    at DmnoCommand.parseAsync (D:\_dev\astro-playground\astro-nomy\node_modules\dmno\node_modules\commander\lib\command.js:1092:5)
    at file:///D:/_dev/astro-playground/astro-nomy/node_modules/dmno/src/cli/commands/init.command.ts:171:9

### System Info

```shell
win32, bun 1.1.24, astro
```

**Comment by theoephraim** [comment]
Closing for now - I think we tracked these issues down to windows support? For now we'll just recommend using WSL2.

Please reopen if you encounter similar with WSL2.
